version: "3.8"

volumes:
  api-db-data:

networks:
  api-network:

services:
  db:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - api-db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - "${DB_PORT}:5432"
    networks:
      - api-network

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - API_PORT=${API_PORT} 
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    command: >
      bash -c "/usr/bin/psql postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}
      -c 'drop database if exists ${DB_NAME}' && /usr/bin/psql
      postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT} -c 'create database ${DB_NAME}'"
    networks:
      - api-network
